AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
