name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec
    strategy:
      matrix:
        ruby:
          - '3.3.1'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Spec task
      run: bundle exec rake spec

  lint:
    runs-on: ubuntu-latest
    name: lint
    strategy:
      matrix:
        ruby:
          - '3.3.1'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: lint tasp
      run: bundle exec rake rubocop
